-- Specialty kind + hub cover images for academic offer hub
ALTER TABLE specialties
  ADD COLUMN kind ENUM('EXPLORATORY_WORKSHOP', 'TECHNICAL_SPECIALTY')
  NOT NULL DEFAULT 'TECHNICAL_SPECIALTY'
  AFTER status;

CREATE TABLE IF NOT EXISTS specialty_hub_covers (
  kind ENUM('EXPLORATORY_WORKSHOP', 'TECHNICAL_SPECIALTY') NOT NULL,
  image_path VARCHAR(500) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (kind)
);

INSERT INTO specialty_hub_covers (kind, image_path)
VALUES
  ('EXPLORATORY_WORKSHOP', NULL),
  ('TECHNICAL_SPECIALTY', NULL)
ON DUPLICATE KEY UPDATE kind = kind;
