export const PERMISSIONS = {
  ADMINISTRATOR_VIEW: 'administrator.view',
  ADMINISTRATOR_CREATE: 'administrator.create',
  ADMINISTRATOR_EDIT: 'administrator.edit',
  ADMINISTRATOR_DELETE: 'administrator.delete',
  ADMINISTRATOR_EXPORT: 'administrator.export',
  ADMINISTRATOR_CONFIGURE: 'administrator.configure',
  ACADEMIC_STRUCTURE_VIEW: 'academic_structure.view',
  ACADEMIC_STRUCTURE_CREATE: 'academic_structure.create',
  ACADEMIC_STRUCTURE_EDIT: 'academic_structure.edit',
  PERIODS_VIEW: 'periods.view',
  PERIODS_CREATE: 'periods.create',
  PERIODS_EDIT: 'periods.edit',
  SECTIONS_VIEW: 'sections.view',
  SECTIONS_CREATE: 'sections.create',
  SECTIONS_EDIT: 'sections.edit',
  SPECIALTIES_VIEW: 'specialties.view',
  SPECIALTIES_CREATE: 'specialties.create',
  SPECIALTIES_EDIT: 'specialties.edit',
  ROLES_PERMISSIONS_VIEW: 'roles_permissions.view',
  ROLES_PERMISSIONS_CREATE: 'roles_permissions.create',
  ROLES_PERMISSIONS_EDIT: 'roles_permissions.edit',
  ROLES_PERMISSIONS_DELETE: 'roles_permissions.delete',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_READ: 'students.view',
  STUDENTS_UPDATE: 'students.edit',
  ATTENDANCE_REGISTER: 'attendance.create',
  ATTENDANCE_READ: 'attendance.view',
  DISCIPLINARY_CREATE: 'disciplinary.create',
  DISCIPLINARY_READ: 'disciplinary.view',
  COMMUNICATIONS_CREATE: 'communications.create',
  COMMUNICATIONS_READ: 'communications.view',
  APPEALS_CREATE: 'appeals.create',
  APPEALS_REVIEW: 'appeals.edit',
  APPEALS_RESOLVE: 'appeals.configure',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS] | string;
