export enum PermissionModule {
  ADMINISTRATOR = 'ADMINISTRATOR',
  ACADEMIC_STRUCTURE = 'ACADEMIC_STRUCTURE',
  PERIODS = 'PERIODS',
  ATTENDANCE = 'ATTENDANCE',
  STUDENTS = 'STUDENTS',
  DISCIPLINARY = 'DISCIPLINARY',
  COMMUNICATIONS = 'COMMUNICATIONS',
  APPEALS = 'APPEALS',
  ROLES_PERMISSIONS = 'ROLES_PERMISSIONS',
  SPECIALTIES = 'SPECIALTIES',
  SECTIONS = 'SECTIONS',
}
